### ISSUE TITLE
`Vacancy.query` as an array

### ISSUE THREAD

**Issue by zhukovsd** [IT-job-market-analytics/vacancy-storage-service#11]
- [x] Vacancy query as an array
- [x] Multikey index for `query` to find vacancies by a given query - https://www.mongodb.com/docs/manual/core/index-multikey/
- [x] On receiving RabbitMQ messages, insert new record or update an existing
- [x] Add `find by query` method to Spring Data repository
- [x] Populate the table with sample data (100+ items)
- [x] Use MongoDB `explain` to check if `find by query` method uses multikey index - https://www.mongodb.com/docs/manual/reference/command/explain/

**Comment by RomanV79** [comment]
populate file: populate-mongoDB.txt (near: test-rabbitmq-requests.http)

explain in console:
```
db.vacancy.find({"queries" : "Java"}).explain("executionStats")
```

result:
```
"nReturned": 58,
      "executionTimeMillis": 0,
      "totalKeysExamined": 58,
      "totalDocsExamined": 58,
```

we find 58 documents from indexed 58.. not from all 150

**Comment by zhukovsd** [comment]
Explain for `QueriesContains` request:
```
db.vacancy.find({"queries" : { "$in" : ["Kotlin"]}}).explain("executionStats")
```
