### ISSUE TITLE
Store vacancies to MongoDB

### ISSUE THREAD

**Issue by zhukovsd** [IT-job-market-analytics/vacancy-storage-service#6]
- [x] Define entity for a vacancy. Entity is a separate class(es) based on DTOs
- [x] Research ModelMapper/MapStruct for DTO->Entity conversion
- [x] Create vacancy MongoDB repository
- [x] In RabbitMQ listener - convert DTO to entity, set TTL for entity (take TTL value from config) store entity to repository

**Comment by RomanV79** [comment]
1. What field must be indexed with TTL: createdAt or publishedAt? 
2. What should we do if required indexed field will be null?
3. I need Salary fields in final reliase. Now it looks like: salary='{from=40000, to=null, currency=RUR, gross=false} .
4. Can we recieve old vacancies from queue? Should I check if it is a new vacancy for save or old vacancy for update?

**Comment by RomanV79** [comment]
point 3 - done

**Comment by zhukovsd** [comment]
> 1. What field must be indexed with TTL: createdAt or publishedAt?

`publishedAt`

> 2. What should we do if required indexed field will be null?

Mongo can index null fields just fine. In our case, we create indexes for `publishedAt` and `query`.

> 4. Can we recieve old vacancies from queue? Should I check if it is a new vacancy for save or old vacancy for update?

We can. This will be the subject of one of the next tasks.

**Comment by RomanV79** [comment]
Need understanding which fields we need to store in Vacancy Model, than make matrix-fields and compare DTO and Model classes.
